name: sms_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus: ^3.0.3
  telephony:
    git:
      url: https://github.com/suhardik/s_telephony.git
      ref: develop
  readsms: ^0.0.2+2
  battery_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
